# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files", "--project=airoot"]

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black
