[project]
name = "airoot"
version = "0.0.0"
authors = [
    { name="Ramya Kottapalli", email="rskottap@gmail.com" },
]
description = "Suite of generation models for text, image, audio and video."
dependencies = [
    "pytest",
    "python-magic",
    "diffusers[torch]",
    "Pillow",
    "transformers",
    "accelerate",
    "optimum",
    "assure",
    "mmry",
]

[project.optional-dependencies]
dev = [
    "black>=23.9.1",
    "isort>=5.10.1",
    "pre-commit",
]

[tool.black]
line-length = 80

[project.urls]
source = "https://github.com/rskottap/airoot"
download = "https://pypi.org/project/airoot/#files"

[project.scripts]
textgen       = "textgen.__main__:main"
