[project]
name = "airoot"
version = "0.0.0"
authors = [
    { name="Ramya Kottapalli", email="rskottap@gmail.com" },
]
description = "Suite of generation models for text, image, audio and video."
dependencies = [
    "pytest",
    "Pillow",
    "transformers",
    "assure",
    "mmry",
]

[project.urls]
source = "https://github.com/rskottap/airoot"
download = "https://pypi.org/project/airoot/#files"

[project.scripts]
input       = "airrot.__main__:main"
